<a href="https://colab.research.google.com/github/vchibilisco/ejemplos-IA/blob/master/red_neuronal/NN_sigmoid_y_FC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy

In [2]:

def neurona(x1, x2, w1, w2, b):
  z = w1 * x1 + w2 * x2 + b
  return sigmoid(z)

def sigmoid(x):
  return 1/(1 + numpy.exp(-x))

In [3]:
w1 = numpy.random.randn()
w2 = numpy.random.randn()
b = numpy.random.randn()
print(w1)
print(w2)
print(b)

-1.1472545035187736
-0.036556620523641746
0.17029024221372918


In [4]:
pred = neurona(3, 1.5, w1, w2, b)
pred

0.03467960836953989

In [ ]:
pred = neurona(2, 1, w1, w2 ,b)
pred

0.9119784910567738

In [5]:
pred = neurona(4, 1.5, w1, w2, b)
pred

0.011277961775823379

In [6]:
# Funcion costo
# La función de coste trata de determinar
# el error entre el valor estimado y el valor real,
# con el fin de optimizar los parámetros de la red neuronal
# (pred - Y_esperado)^2 Error cuadratico

# Minimizar, se realiza cambiando los pesos
Y_esperado = 4
pred = neurona(2, 1, w1, w2 ,b)
m = 1
print(pred)
def cost(b):
  J = (1/(2 * m)) * (b - Y_esperado) ** 2
  return J

cost(pred)

0.10332858851733583


7.59202404453315

In [7]:
#Ejemplo precio de casas basado en m2

# 200m2 , $15000
# 230m2 , $18000
# 100m2 , $10000
# 150m2 , $13000

# Definir X
X = numpy.array([
     [200, 2],
     [230, 3],
     [100, 1],
     [150, 1]
    ])

print(X)
X.shape

[[200   2]
 [230   3]
 [100   1]
 [150   1]]


(4, 2)

In [8]:
# Definir Y
Y = numpy.array([
     15000,
     18000,
     10000,
     13000
])

print(Y)

Y.shape

[15000 18000 10000 13000]


(4,)

In [9]:

# Definir W , cantidad de caracteristicas + 1
W = numpy.array([numpy.random.rand(
    numpy.size(X,1) + 1
)])
print(W)
W.shape

[[0.44173029 0.01657851 0.58747523]]


(1, 3)

In [14]:
def capaDeNeurona(X, W):
  arregloDeUnos = numpy.array(
    numpy.ones(
        (numpy.size(X,0),1),
        dtype=int
        )
  )
  X_red = numpy.append(arregloDeUnos, X, axis=1)

  X_transpuesta = X_red.transpose()

  #print(f'shape W:\n{W.shape}')
  #print(f'shape X_transpuesta:\n{X_transpuesta.shape}')
  z = numpy.matmul(W, X_transpuesta)
  
  #print(f'shape z:\n{z.shape}')
  #print(f'Value z:\n{z}')
  a = sigmoid(z)
  return a

In [15]:
prediction = capaDeNeurona(X, W)
prediction

array([[0.9928423 , 0.99756947, 0.93625855, 0.9711391 ]])

In [16]:
def costMatriz(pred, Y):
  m = len(Y)
  diff = (pred - Y) ** 2

  #print(f'diff:\n{diff}')

  J = (1/(2 * m)) * numpy.sum(diff)
  return J

In [17]:
costMatriz(prediction, Y)

102236291.40536226