<a href="https://colab.research.google.com/github/vchibilisco/ejemplos-IA/blob/master/red_neuronal/NN_y_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Calcule las salidas de la capa de neuronas

In [7]:
import numpy as np

In [8]:
X = np.array([2, 1, -3,1])
X

array([ 2,  1, -3,  1])

In [9]:
W = np.array([[0.5 , 1 ,2, 3], [3, -1, -2, -5]])
W

array([[ 0.5,  1. ,  2. ,  3. ],
       [ 3. , -1. , -2. , -5. ]])

In [10]:
z = np.matmul(W, X)
z

array([-1.,  6.])

In [11]:
np.maximum(0,z)

array([0., 6.])

Calcule la cantidad de parámetros de la siguiente red neuronal.


In [12]:
from keras import Sequential
from keras.layers import Dense

In [13]:
model = Sequential()
model.add(Dense(5, input_dim=10, activation='tanh'))
model.add(Dense(4, activation='tanh'))
model.add(Dense(3, activation='softmax'))

model.summary()

c:\Users\vicen\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 5)              │            55 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4)              │            24 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 94 (376.00 B)

 Trainable params: 94 (376.00 B)

 Non-trainable params: 0 (0.00 B)

Vector de Probabilidad

In [14]:
import numpy as np

In [15]:
Z = np.array([2, -1, 1])
Z

array([ 2, -1,  1])

In [16]:
t = np.exp(Z)
t

array([7.3890561 , 0.36787944, 2.71828183])

In [17]:
t/np.sum(t)

array([0.70538451, 0.03511903, 0.25949646])