<a href="https://colab.research.google.com/github/vchibilisco/ejemplos-IA/blob/master/red_neuronal/NN_y_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Calcule las salidas de la capa de neuronas

In [1]:
import numpy as np

In [2]:
X = np.array([2, 1, -3,1])
X

array([ 2,  1, -3,  1])

In [3]:
W = np.array([[0.5 , 1 ,2, 3], [3, -1, -2, -5]])
W

array([[ 0.5,  1. ,  2. ,  3. ],
       [ 3. , -1. , -2. , -5. ]])

In [4]:
z = np.matmul(W, X)
z

array([-1.,  6.])

In [5]:
np.maximum(0,z)

array([0., 6.])

Calcule la cantidad de parámetros de la siguiente red neuronal.


In [6]:
from keras import Sequential
from keras.layers import Dense

In [7]:
model = Sequential()
model.add(Dense(5, input_dim=10, activation='tanh'))
model.add(Dense(4, activation='tanh'))
model.add(Dense(3, activation='softmax'))

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 5)                 55        
_________________________________________________________________
dense_1 (Dense)              (None, 4)                 24        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 15        
Total params: 94
Trainable params: 94
Non-trainable params: 0
_________________________________________________________________


Vector de Probabilidad

In [8]:
import numpy as np

In [9]:
Z = np.array([2, -1, 1])
Z

array([ 2, -1,  1])

In [10]:
t = np.exp(Z)
t

array([7.3890561 , 0.36787944, 2.71828183])

In [11]:
t/np.sum(t)

array([0.70538451, 0.03511903, 0.25949646])